<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHEBKaF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHEBKaF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLHEBKaF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLHEBKaF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLHEBKaF\appAppKernelProdContainer([
    'container.build_hash' => 'LHEBKaF',
    'container.build_id' => '4d181d82',
    'container.build_time' => 1741965905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHEBKaF');
