<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHoETHr\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHoETHr/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHoETHr.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHoETHr\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerKHoETHr\appAppKernelDevDebugContainer([
    'container.build_hash' => 'KHoETHr',
    'container.build_id' => '97d51220',
    'container.build_time' => 1739682359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHoETHr');
