<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArtHvhqLeh/LHcxQcZ2oF'."\n".'d2MhqoX48XMKV+Dze048GApZM+5Q6DUGAfAUusR4ZBJ1BlgUHF3vGXxN1NSXjcX0'."\n".'M8JKzY9UI5wAJMfWPpmEbiqeKHNIUGfVuUadQuKkCw0KccLrPq/ts3kZlTiaBxkJ'."\n".'PPdpziJUHt+LlvJMvPmvrPWUghlHDLuAXUjNTU09Mzpss3zfS3Np7MvcODV01rYe'."\n".'DvXit+uyy1xAIub7eqtQh1+u4ayY091BizBOnD6kX45dSJ0XdRki8l/lJg/TjcaU'."\n".'dyQF83JPVAhdihnCn6hAi1KzdNlf9veKwX150BSBhurMsgDRTgE+NhQ1pd7bZXsw'."\n".'3QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
